### ISSUE TITLE
Installing Libraries

### ISSUE THREAD

**Issue by AyoCJ** [aidandenlinger/SnapchatMemoriesMetadataAdder#1]
Downloaded the ffmpeg & vips-dev compiled libraries as I'm on Windows, but I have no idea what to do with them?

**Comment by aidandenlinger** [comment]
Hi! You'll need to add the compiled libraries to your PATH - it's a list of folders that Windows `cmd` looks in for programs to execute. [Here's instructions for how to add ffmpeg to your PATH on Windows, it should be a similar set of instructions to add the vips exe](https://video.stackexchange.com/a/20496) (or you could just add the vips.exe file to the same folder that ffmpeg.exe is in, and then both exes will be on your path.) Once they're on your PATH, the script should be able to find and use them. If/when you delete this folder, you should also delete it from your path.

Let me know if this works - I'm not running Windows, so I didn't have to do this myself. If it works, I'll add this info to the README.

(Alternatively, if you have a [Windows Subsystem for Linux install](https://learn.microsoft.com/en-us/windows/wsl/install) around, you could use that instead and install ffmpeg/vips with the distro's package manager.)

**Comment by aidandenlinger** [comment]
I did some more research and added some more installation information in a146b60 and a04b8e5 - let me know if there's anything else I can help with :)

**Comment by aidandenlinger** [comment]
Closing for now due to inactivity, feel free to open a new issue if there's anything else I can help with :)
